services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"